[versions]
livemap = "0.0.1-SNAPSHOT"

annotations = "26.0.2-1"      # https://github.com/JetBrains/java-annotations
fix-javadoc = "1.19"          # https://github.com/mfnalex/gradle-fix-javadoc-plugin
shadowJar = "9.3.1"           # https://github.com/GradleUp/shadow
simpleYaml = "1.8.4"          # https://github.com/Carleslc/Simple-YAML
undertow = "2.3.21.Final"     # https://github.com/undertow-io/undertow

[plugins]
fix-javadoc = { id = "com.jeff-media.fix-javadoc-plugin", version.ref = "fix-javadoc" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadowJar" }

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
simpleYaml = { group = "com.github.Carleslc.Simple-YAML", name = "Simple-Yaml", version.ref = "simpleYaml" }
undertow = { group = "io.undertow", name = "undertow-core", version.ref = "undertow" }
